/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-03-04 at 11:32:09 UTC 
 * Modify at your own risk.
 */

package teo.friendidentifier.dataentityendpoint;

/**
 * Service definition for Dataentityendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link DataentityendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Dataentityendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the dataentityendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://friend-finder-engine-teo.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "dataentityendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Dataentityendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Dataentityendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getDataEntity".
   *
   * This request holds the parameters needed by the the dataentityendpoint server.  After setting any
   * optional parameters, call the {@link GetDataEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetDataEntity getDataEntity(java.lang.String id) throws java.io.IOException {
    GetDataEntity result = new GetDataEntity(id);
    initialize(result);
    return result;
  }

  public class GetDataEntity extends DataentityendpointRequest<teo.friendidentifier.dataentityendpoint.model.DataEntity> {

    private static final String REST_PATH = "dataentity/{id}";

    /**
     * Create a request for the method "getDataEntity".
     *
     * This request holds the parameters needed by the the dataentityendpoint server.  After setting
     * any optional parameters, call the {@link GetDataEntity#execute()} method to invoke the remote
     * operation. <p> {@link GetDataEntity#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetDataEntity(java.lang.String id) {
      super(Dataentityendpoint.this, "GET", REST_PATH, null, teo.friendidentifier.dataentityendpoint.model.DataEntity.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetDataEntity setAlt(java.lang.String alt) {
      return (GetDataEntity) super.setAlt(alt);
    }

    @Override
    public GetDataEntity setFields(java.lang.String fields) {
      return (GetDataEntity) super.setFields(fields);
    }

    @Override
    public GetDataEntity setKey(java.lang.String key) {
      return (GetDataEntity) super.setKey(key);
    }

    @Override
    public GetDataEntity setOauthToken(java.lang.String oauthToken) {
      return (GetDataEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public GetDataEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetDataEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetDataEntity setQuotaUser(java.lang.String quotaUser) {
      return (GetDataEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetDataEntity setUserIp(java.lang.String userIp) {
      return (GetDataEntity) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetDataEntity setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetDataEntity set(String parameterName, Object value) {
      return (GetDataEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertDataEntity".
   *
   * This request holds the parameters needed by the the dataentityendpoint server.  After setting any
   * optional parameters, call the {@link InsertDataEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link teo.friendidentifier.dataentityendpoint.model.DataEntity}
   * @return the request
   */
  public InsertDataEntity insertDataEntity(teo.friendidentifier.dataentityendpoint.model.DataEntity content) throws java.io.IOException {
    InsertDataEntity result = new InsertDataEntity(content);
    initialize(result);
    return result;
  }

  public class InsertDataEntity extends DataentityendpointRequest<teo.friendidentifier.dataentityendpoint.model.DataEntity> {

    private static final String REST_PATH = "dataentity";

    /**
     * Create a request for the method "insertDataEntity".
     *
     * This request holds the parameters needed by the the dataentityendpoint server.  After setting
     * any optional parameters, call the {@link InsertDataEntity#execute()} method to invoke the
     * remote operation. <p> {@link InsertDataEntity#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link teo.friendidentifier.dataentityendpoint.model.DataEntity}
     * @since 1.13
     */
    protected InsertDataEntity(teo.friendidentifier.dataentityendpoint.model.DataEntity content) {
      super(Dataentityendpoint.this, "POST", REST_PATH, content, teo.friendidentifier.dataentityendpoint.model.DataEntity.class);
    }

    @Override
    public InsertDataEntity setAlt(java.lang.String alt) {
      return (InsertDataEntity) super.setAlt(alt);
    }

    @Override
    public InsertDataEntity setFields(java.lang.String fields) {
      return (InsertDataEntity) super.setFields(fields);
    }

    @Override
    public InsertDataEntity setKey(java.lang.String key) {
      return (InsertDataEntity) super.setKey(key);
    }

    @Override
    public InsertDataEntity setOauthToken(java.lang.String oauthToken) {
      return (InsertDataEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertDataEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertDataEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertDataEntity setQuotaUser(java.lang.String quotaUser) {
      return (InsertDataEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertDataEntity setUserIp(java.lang.String userIp) {
      return (InsertDataEntity) super.setUserIp(userIp);
    }

    @Override
    public InsertDataEntity set(String parameterName, Object value) {
      return (InsertDataEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listDataEntity".
   *
   * This request holds the parameters needed by the the dataentityendpoint server.  After setting any
   * optional parameters, call the {@link ListDataEntity#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListDataEntity listDataEntity() throws java.io.IOException {
    ListDataEntity result = new ListDataEntity();
    initialize(result);
    return result;
  }

  public class ListDataEntity extends DataentityendpointRequest<teo.friendidentifier.dataentityendpoint.model.CollectionResponseDataEntity> {

    private static final String REST_PATH = "dataentity";

    /**
     * Create a request for the method "listDataEntity".
     *
     * This request holds the parameters needed by the the dataentityendpoint server.  After setting
     * any optional parameters, call the {@link ListDataEntity#execute()} method to invoke the remote
     * operation. <p> {@link ListDataEntity#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListDataEntity() {
      super(Dataentityendpoint.this, "GET", REST_PATH, null, teo.friendidentifier.dataentityendpoint.model.CollectionResponseDataEntity.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListDataEntity setAlt(java.lang.String alt) {
      return (ListDataEntity) super.setAlt(alt);
    }

    @Override
    public ListDataEntity setFields(java.lang.String fields) {
      return (ListDataEntity) super.setFields(fields);
    }

    @Override
    public ListDataEntity setKey(java.lang.String key) {
      return (ListDataEntity) super.setKey(key);
    }

    @Override
    public ListDataEntity setOauthToken(java.lang.String oauthToken) {
      return (ListDataEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public ListDataEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListDataEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListDataEntity setQuotaUser(java.lang.String quotaUser) {
      return (ListDataEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListDataEntity setUserIp(java.lang.String userIp) {
      return (ListDataEntity) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListDataEntity setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListDataEntity setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListDataEntity set(String parameterName, Object value) {
      return (ListDataEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeDataEntity".
   *
   * This request holds the parameters needed by the the dataentityendpoint server.  After setting any
   * optional parameters, call the {@link RemoveDataEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveDataEntity removeDataEntity(java.lang.String id) throws java.io.IOException {
    RemoveDataEntity result = new RemoveDataEntity(id);
    initialize(result);
    return result;
  }

  public class RemoveDataEntity extends DataentityendpointRequest<Void> {

    private static final String REST_PATH = "dataentity/{id}";

    /**
     * Create a request for the method "removeDataEntity".
     *
     * This request holds the parameters needed by the the dataentityendpoint server.  After setting
     * any optional parameters, call the {@link RemoveDataEntity#execute()} method to invoke the
     * remote operation. <p> {@link RemoveDataEntity#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveDataEntity(java.lang.String id) {
      super(Dataentityendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveDataEntity setAlt(java.lang.String alt) {
      return (RemoveDataEntity) super.setAlt(alt);
    }

    @Override
    public RemoveDataEntity setFields(java.lang.String fields) {
      return (RemoveDataEntity) super.setFields(fields);
    }

    @Override
    public RemoveDataEntity setKey(java.lang.String key) {
      return (RemoveDataEntity) super.setKey(key);
    }

    @Override
    public RemoveDataEntity setOauthToken(java.lang.String oauthToken) {
      return (RemoveDataEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveDataEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveDataEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveDataEntity setQuotaUser(java.lang.String quotaUser) {
      return (RemoveDataEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveDataEntity setUserIp(java.lang.String userIp) {
      return (RemoveDataEntity) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveDataEntity setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveDataEntity set(String parameterName, Object value) {
      return (RemoveDataEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateDataEntity".
   *
   * This request holds the parameters needed by the the dataentityendpoint server.  After setting any
   * optional parameters, call the {@link UpdateDataEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link teo.friendidentifier.dataentityendpoint.model.DataEntity}
   * @return the request
   */
  public UpdateDataEntity updateDataEntity(teo.friendidentifier.dataentityendpoint.model.DataEntity content) throws java.io.IOException {
    UpdateDataEntity result = new UpdateDataEntity(content);
    initialize(result);
    return result;
  }

  public class UpdateDataEntity extends DataentityendpointRequest<teo.friendidentifier.dataentityendpoint.model.DataEntity> {

    private static final String REST_PATH = "dataentity";

    /**
     * Create a request for the method "updateDataEntity".
     *
     * This request holds the parameters needed by the the dataentityendpoint server.  After setting
     * any optional parameters, call the {@link UpdateDataEntity#execute()} method to invoke the
     * remote operation. <p> {@link UpdateDataEntity#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link teo.friendidentifier.dataentityendpoint.model.DataEntity}
     * @since 1.13
     */
    protected UpdateDataEntity(teo.friendidentifier.dataentityendpoint.model.DataEntity content) {
      super(Dataentityendpoint.this, "PUT", REST_PATH, content, teo.friendidentifier.dataentityendpoint.model.DataEntity.class);
    }

    @Override
    public UpdateDataEntity setAlt(java.lang.String alt) {
      return (UpdateDataEntity) super.setAlt(alt);
    }

    @Override
    public UpdateDataEntity setFields(java.lang.String fields) {
      return (UpdateDataEntity) super.setFields(fields);
    }

    @Override
    public UpdateDataEntity setKey(java.lang.String key) {
      return (UpdateDataEntity) super.setKey(key);
    }

    @Override
    public UpdateDataEntity setOauthToken(java.lang.String oauthToken) {
      return (UpdateDataEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateDataEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateDataEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateDataEntity setQuotaUser(java.lang.String quotaUser) {
      return (UpdateDataEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateDataEntity setUserIp(java.lang.String userIp) {
      return (UpdateDataEntity) super.setUserIp(userIp);
    }

    @Override
    public UpdateDataEntity set(String parameterName, Object value) {
      return (UpdateDataEntity) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Dataentityendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Dataentityendpoint}. */
    @Override
    public Dataentityendpoint build() {
      return new Dataentityendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link DataentityendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setDataentityendpointRequestInitializer(
        DataentityendpointRequestInitializer dataentityendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(dataentityendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
